### ISSUE TITLE
Dependency just changed to php 7.4 requirement

### ISSUE THREAD

**Issue by parljohn** [Jean85/pretty-package-versions#20] opened 2020-05-29 18:39 UTC
The orcas dependency has changed its required to php 7.4 which we have not upgraded to yet and will not be able to any time soon.  We're just trying to use the sentry/sdk plugin which requires your module so now we're stuck.  Is there a way around this?

**Comment by Jean85** [comment] 2020-06-03 11:11
I'm not sure I understood but I'll try to answer: are you talking about Ocramius' dependency? That package require 7.4 only in the latest minor, Composer is able to avoid installing that version if you're not using PHP 7.4 yet.

**Comment by dereuromark** [comment] 2020-06-11 12:54
@Jean85 But soon the bugfixes and critical fixes will only be there on top of that, making that dependency invalid/broken by design.

Tip: https://github.com/dereuromark/composer-prefer-lowest will also show this if you run it in prefer lowest travis run. It shows where the "dependencies promised" do not match the reality - and what part of it cannot be tested anymore either in terms of compatibility in that PHP version.

**Comment by Jean85** [comment] 2020-06-11 15:49
Patches (especially critical ones) are still possible on older version of Ocramius' package, so no problem there.

Also, my package in v1.3 relies on a fork that backports the compat for older PHP version, and in v1.4 now relies on Composer 2 directly, with no dependencies in the middle.

This issue comes up a lot (see my reply on a similar issue here https://github.com/getsentry/sentry-laravel/issues/335#issuecomment-629132274), and stems from a misconception on how dependencies should be handled, and what SemVer says about changing/bumping deps requirements:
 * bumping requirements is not a BC
 * so it can be done in majors
 * it has to be done in minors though, to allow patches, even backported ones if needed
 * if you rely on a dependency of your dependency, that's called a "transient dependency", and you shouldn't do it because it can break your app
 * you should counter transient dependencies with https://github.com/maglnet/ComposerRequireChecker/

So I don't see the issue here.

**Comment by Jean85** [comment] 2020-06-11 15:54
PS: happy to accept a PR which adds a check with `dereuromark/composer-prefer-lowest`, so we can see that the prefer-lowest still allows versions for any possible PHP version that is declared as minimum supported.

**Comment by Jean85** [comment] 2020-06-19 15:39
Closing since thanks to #21 I changed my mind on the release schedule, and I will release Composer 2 compat as 2.0 anyway.

**Closed by Jean85** 2020-06-19 15:39 UTC
Labels: invalid
