### ISSUE TITLE
Version of the root package is displayed incorrectly

### ISSUE THREAD

**Issue by morozov** [Jean85/pretty-package-versions#3] opened 2017-11-20 07:25 UTC
```
↪ wget https://github.com/phpstan/phpstan/releases/download/0.8.5/phpstan.phar

↪ php phpstan.phar --version
PHPStan - PHP Static Analysis Tool 0.8.5.0
```

The tag name is `0.8.5` according to the URL but the displayed version is `0.8.5.0`. The same can be seen with any other application using `\Jean85\PrettyVersions::getVersion('vendor/package')->getPrettyVersion();` where the vendor/package is the app itself.

Looks like when building the version from a git tag, [composer/semver](https://github.com/composer/semver) pads the version with zeros to have at least 4 numbers (see https://github.com/composer/semver/commit/c1f064e9b79ccac4e5ee4980df97bdbfd2c41918#diff-b25d417df293a1cf205697536aed0410R33).

Not sure if the original tag can be restored from the padded version, but I'd say that most of the packages have 3 numbers in their version, so it should be safe to cut off the trailing zero. Unless there's a better solution.

**Comment by Jean85** [comment] 2017-11-20 10:11
Umh, this is really strange, because the issue seems to be happening only with the PHAR. I have the same version installed on some of my project, and this is the output:
```
$ phpstan --version
PHPStan - PHP Static Analysis Tool 0.8.5
```

**Comment by morozov** [comment] 2017-11-20 15:38
@Jean85 if the same version is installed as a composer dependency, the issue will be not reproducible because it's not a root package in this case. If you start a new git repo and tag a version, then even without packaging a PHAR you'll see the same issue.

```
git init
cat > composer.json <<EOF
{
    "name": "test/test",
    "require": {
        "jean85/pretty-package-versions": "^1.0.2"
    }
}
EOF

cat > main.php  <<EOF
<?php

require __DIR__ . '/vendor/autoload.php';
echo \Jean85\PrettyVersions::getVersion('test/test')->getPrettyVersion(), PHP_EOL;
EOF

git add .
git commit -mTest
git tag 1.2.3
git checkout 1.2.3
composer install
php main.php

>> 1.2.3.0
```

**Comment by Jean85** [comment] 2017-11-21 08:56
Umh, that's annoying. In this way I'm not sure there's something I can leverage to discern if the requested package is the root one...

**Comment by morozov** [comment] 2017-11-21 16:26
I see at least two solutions:
1. During a package installation hook into the process and store the information about the root package
   ```php
   public static function handler(Event $composerEvent)
   {
       $root = $composerEvent->getComposer()->getPackage();
   }
   ```
   Then use this when printing the version.
2. Less reliable but easier to implement. In the [current implementation of `PackageVersions`](https://github.com/Ocramius/PackageVersions/blob/13a5686539697b20996dc907238d546819e7ed9e/src/PackageVersions/Installer.php#L180), the root package is always the last one.

Alternatively, the logic of building package versions could be augmented, so that instead of the value returned by `$rootPackage->getVersion()`, the value of `$rootPackage->getPrettyVersion()` or `$rootPackage->getFullPrettyVersion()` was dumped and then displayed without any parsing.

That last approach looks the hardest but the more correct to me.

**Comment by Jean85** [comment] 2017-11-22 08:47
Both the first and last approach would require transforming this package from a simple wrapper into a composer plugin on its own, re-doing the work of `ocramius/package-versions`, which is not ideal; approach number two is not reliable... I'll dig into the normalization to see if I'm able to intercept all the meaningful cases.

**Comment by Jean85** [comment] 2017-11-22 09:42
I've opened https://github.com/Ocramius/PackageVersions/pull/51 that may solve the root cause of this issue.

**Comment by Jean85** [comment] 2017-11-30 22:08
Fixed with the [1.0.3 release](https://github.com/Jean85/pretty-package-versions/releases/tag/1.0.3).

**Comment by morozov** [comment] 2017-11-30 22:41
Thank you @Jean85 for taking care!

**Comment by morozov** [comment] 2017-12-02 22:16
The issue seems regressed by https://github.com/composer/composer/commit/5ba6d7d4364b0d1898017436935b863d4d8fb14d#diff-8b93719582669d35594f58bb11eed1d2R93. In the highlighted line, the pretty version is rebuilt from the normalized one, so the trailing zero is re-added back.

**Comment by Jean85** [comment] 2017-12-04 11:52
I've opened https://github.com/composer/composer/pull/6866 that should finally fix this.

**Comment by Jean85** [comment] 2018-02-27 16:31
composer/composer#6866 has been closed, hence this is resolved.

**Closed by Jean85** 2018-02-27 16:31 UTC
